--liquibase formatted sql
--changeset efragance:create-table-FORMULA_SUBSTANCES-v1.0.1
DROP TABLE IF EXISTS `FORMULA_SUBSTANCES`;
CREATE TABLE `FORMULA_SUBSTANCES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CREATED_DATE` datetime(6) NOT NULL,
  `MODIFIED_BY` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `MODIFIED_DATE` datetime(6) NOT NULL,
  `VERSION` bigint(20) NOT NULL,
  `ANNEXED_ID` bigint(20) NOT NULL,
  `FORMULA_ID` bigint(20) NOT NULL,
  `PERCENTAGE` decimal(5,0) NOT NULL,
  `SUBSTANCE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKqw4ceh3ln2sbslo056t3j9bok` (`ANNEXED_ID`),
  KEY `FKcimx5x5odusq1o3e73f8v6x0y` (`FORMULA_ID`),
  KEY `FKbgue36o50k6x31v1w1pox9csi` (`SUBSTANCE_ID`),
  CONSTRAINT `FKbgue36o50k6x31v1w1pox9csi` FOREIGN KEY (`SUBSTANCE_ID`) REFERENCES `SUBSTANCES` (`ID`),
  CONSTRAINT `FKcimx5x5odusq1o3e73f8v6x0y` FOREIGN KEY (`FORMULA_ID`) REFERENCES `FORMULAS` (`ID`),
  CONSTRAINT `FKqw4ceh3ln2sbslo056t3j9bok` FOREIGN KEY (`ANNEXED_ID`) REFERENCES `ANNEXES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci