--liquibase formatted sql
--changeset efragance:create-table-DILUTIONS_REL-v1.0.1
DROP TABLE IF EXISTS `DILUTIONS_REL`;
CREATE TABLE `DILUTIONS_REL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CREATED_DATE` datetime(6) NOT NULL,
  `MODIFIED_BY` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `MODIFIED_DATE` datetime(6) NOT NULL,
  `VERSION` bigint(20) NOT NULL,
  `DILUTION_ID` bigint(20) NOT NULL,
  `QUANTITY` decimal(5,0) NOT NULL,
  `RELATION_LEVEL` int(11) DEFAULT NULL,
  `SUBDILUTION_ID` bigint(20) NOT NULL,
  `SUBDILUTION_PARENT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK6ttkisuxwwrg2a5dhsqn904vv` (`DILUTION_ID`),
  KEY `FK4ylq8q5ju4auulp17cj3icx9c` (`SUBDILUTION_ID`),
  KEY `FK3aer2cfaslwofmmqen3883sp4` (`SUBDILUTION_PARENT_ID`),
  CONSTRAINT `FK3aer2cfaslwofmmqen3883sp4` FOREIGN KEY (`SUBDILUTION_PARENT_ID`) REFERENCES `DILUTIONS` (`ID`),
  CONSTRAINT `FK4ylq8q5ju4auulp17cj3icx9c` FOREIGN KEY (`SUBDILUTION_ID`) REFERENCES `DILUTIONS` (`ID`),
  CONSTRAINT `FK6ttkisuxwwrg2a5dhsqn904vv` FOREIGN KEY (`DILUTION_ID`) REFERENCES `DILUTIONS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci