--liquibase formatted sql
--changeset efragance:create-table-DILUTIONS_RAW_MATERIALS_REL-v1.0.1
DROP TABLE IF EXISTS `DILUTIONS_RAW_MATERIALS_REL`;
CREATE TABLE `DILUTIONS_RAW_MATERIALS_REL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CREATED_DATE` datetime(6) NOT NULL,
  `MODIFIED_BY` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `MODIFIED_DATE` datetime(6) NOT NULL,
  `VERSION` bigint(20) NOT NULL,
  `DILUTION_ID` bigint(20) NOT NULL,
  `QUANTITY` decimal(5,0) NOT NULL,
  `RAW_MATERIAL_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKlpye59bahia32bpwwsum8mo16` (`DILUTION_ID`),
  KEY `FKpf3d1nmj6jq90y6w3xpdffux4` (`RAW_MATERIAL_ID`),
  CONSTRAINT `FKlpye59bahia32bpwwsum8mo16` FOREIGN KEY (`DILUTION_ID`) REFERENCES `DILUTIONS` (`ID`),
  CONSTRAINT `FKpf3d1nmj6jq90y6w3xpdffux4` FOREIGN KEY (`RAW_MATERIAL_ID`) REFERENCES `RAW_MATERIALS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci