--liquibase formatted sql
--changeset efragance:insert-users-v1.0.1
INSERT INTO `USERS` (ID,USER_NAME,PASSWORD,NAME,SURNAME1,SURNAME2,ACTIVE,LANG,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION) VALUES (1,'admin','$2a$10$uTfG61odOYnaathOQXhQR.Q9xinHIj9ICmNiw86Td7WTp09BEks/u','Aname','Asurname1','Asurname2',1,'es','system',NOW(),'system',NOW(),0);
INSERT INTO `ROLES` (ID,ROLE_NAME) VALUES (1,'ROLE_ADMIN');
INSERT INTO `ROLES` (ID,ROLE_NAME) VALUES (2,'ROLE_USER');
INSERT INTO `USERS_ROLES` (USER_ID,ROLE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES (1,1,'system',NOW(),'system',NOW());
INSERT INTO `USERS_ROLES` (USER_ID,ROLE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES (1,2,'system',NOW(),'system',NOW());



